<?php

if( function_exists('acf_add_options_page') ) {

	acf_add_options_page('Theme Settings');
	acf_add_options_page('More Theme Settings');

}

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_5a7cb97dbe47f',
	'title' => 'Social Media Test',
	'fields' => array (
		array (
			'key' => 'field_5a7cb988d7ec9',
			'label' => 'Test',
			'name' => 'test',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'social-media-profiles',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class SocialMediaProfiles {
	private $social_media_profiles_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'social_media_profiles_add_plugin_page' ) );
		// add_action( 'admin_init', array( $this, 'social_media_profiles_page_init' ) );
	}

	public function social_media_profiles_add_plugin_page() {
		add_menu_page(
			'Social Media Profiles', // page_title
			'Social Media', // menu_title
			'manage_options', // capability
			'social-media-profiles', // menu_slug
			array( $this, 'social_media_profiles_create_admin_page' ), // function
			'dashicons-smiley', // icon_url
			100 // position
		);
	}

	public function social_media_profiles_create_admin_page() {
		$this->social_media_profiles_options = get_option( 'social_media_profiles_option_name' ); ?>

		<div class="wrap">
			<h2>Social Media Profiles</h2>
			<p>Use this page to save your social media profiles</p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'social_media_profiles_option_group' );
					do_settings_sections( 'social-media-profiles-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function social_media_profiles_page_init() {
		register_setting(
			'social_media_profiles_option_group', // option_group
			'social_media_profiles_option_name', // option_name
			array( $this, 'social_media_profiles_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'social_media_profiles_setting_section', // id
			'Settings', // title
			array( $this, 'social_media_profiles_section_info' ), // callback
			'social-media-profiles-admin' // page
		);

		add_settings_field(
			'test_0', // id
			'Test', // title
			array( $this, 'test_0_callback' ), // callback
			'social-media-profiles-admin', // page
			'social_media_profiles_setting_section' // section
		);
	}

	public function social_media_profiles_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['test_0'] ) ) {
			$sanitary_values['test_0'] = sanitize_text_field( $input['test_0'] );
		}

		return $sanitary_values;
	}

	public function social_media_profiles_section_info() {
		
	}

	public function test_0_callback() {
		printf(
			'<input class="regular-text" type="text" name="social_media_profiles_option_name[test_0]" id="test_0" value="%s">',
			isset( $this->social_media_profiles_options['test_0'] ) ? esc_attr( $this->social_media_profiles_options['test_0']) : ''
		);
	}

}
if ( is_admin() )
	$social_media_profiles = new SocialMediaProfiles();

/* 
 * Retrieve this value with:
 * $social_media_profiles_options = get_option( 'social_media_profiles_option_name' ); // Array of All Options
 * $test_0 = $social_media_profiles_options['test_0']; // Test
 */